name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via Rsync
        uses: Burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr
          path: ./
          remote_path: /home/${{ secrets.SERVER_USER }}/public_html/wellness.developmentalphawizz.com/
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: >
            --exclude '.git*'
            --exclude '.github*'
            --exclude '.env'
            --exclude 'node_modules'

      - name: Restart PM2 App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/public_html/wellness.developmentalphawizz.com/
            pm2 restart 1
            pm2 save
